[project]
authors = ["Cristian Acuña <c.acuna.sepulveda@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "Advanced-MachineLearning-Algorithms"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.2.5,<5"
tensorflow = ">=2.17.0,<3"
jupytext = ">=1.16.4,<2"
