[project]
authors = ["Cristian Acuña <c.acuna.sepulveda@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "Advanced-MachineLearning-Algorithms"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.2.5,<5"
tensorflow = ">=2.17.0,<3"
jupytext = ">=1.16.4,<2"
keras = ">=3.6.0,<4"
matplotlib = ">=3.9.2,<4"
isort = ">=5.13.2,<6"
ruff = ">=0.6.9,<0.7"
ipympl = ">=0.9.4,<0.10"
black = ">=24.10.0,<25"
scikit-learn = ">=1.5.2,<2"
networkx = ">=3.4.2,<4"
